Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

blogs/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^topics/$', views.topics, name='topics'),
    re_path('^new_blog/$', views.new_blog, name='new_blog'),
    re_path('^edit_blog/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
]

users/urls.py
from django.urls import re_path
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    re_path('^login/$', login, {'template_name': 'users/login.html'},
            name='login'),
    re_path('^logout/$', views.logout_view, name='logout'),
    re_path('^register$', views.register, name='register'),
]

blogs/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Text'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import BlogPost
from .forms import BlogPostForm


def index(request):
    return render(request, 'blogs/index.html')


def check_blog_owner(request, blog):
    if blog.owner != request.user:
        raise Http404


def topics(request):
    topics = BlogPost.objects.order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'blogs/topics.html', context)


@login_required
def new_blog(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('blogs:topics'))

    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def edit_blog(request, blog_id):
    blog = BlogPost.objects.get(id=blog_id)
    check_blog_owner(request, blog)
    if request.method != 'POST':
        form = BlogPostForm(instance=blog)
    else:
        form = BlogPostForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:topics'))

    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Blogs</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            BlogPost</a>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'blogs:topics' %}">Blogs</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}.</a></li>
            <li><a href="{% url 'users:logout' %}">log out</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">register</a></li>
            <li><a href="{% url 'users:login' %}">log in</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->

    </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block content %}

  <h3>Edit blog:</h3>
  <form action="{% url 'blogs:edit_blog' blog.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Share your feelings.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to post
    your own Blog, and list the titles about what you're going to write.
  </h2>
  <h2>
    Write anything you want to share with others in your daily life.
  </h2>
{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3>Add a new blog:</h3>

  <form action="{% url 'blogs:new_blog' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add blog</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/topics.html
{% extends "blogs/base.html" %}

{% block header %}
  <h1>Blogs</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for blog in topics %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            {{ blog.date_added|date:'M d, Y H:i' }}
            <small>
              <a href="{% url 'blogs:edit_blog' blog.id %}">edit blog</a>
            </small>
          </h3>
        </div>
        <div class="panel-body">
          {{ blog.title }}:
          {{ blog.text|linebreaks }}
        </div>
      </div> <!-- panel -->
    {% empty %}
      No blogs have been posted yet.
    {% endfor %}
  </ul>

    <h3><a href="{% url 'blogs:new_blog' %}">Add a new blog:</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}